spring.jms.broker-url=tcp://localhost:61616
spring.jms.user=admin
spring.jms.password=admin

spring.datasource.url=jdbc:postgresql://localhost:5432/my_database
spring.datasource.username=postgres
spring.datasource.password=my_secure_password

spring.jpa.hibernate.ddl-auto=update

spring.docker.compose.enabled=false